# Site settings
title: Jared Tulayan
description: >-
  Rutgers Computer Science student
baseurl: ""
url: ""
domain: "jaredtulayan.xyz" # This is here for ease of access 
repo: "https://github.com/Endoman123/jaredtulayan.xyz" # Source link
permalink: /blog/:title:output_ext
highlighter: rouge

# Custom collections
collections:
  projects:
    output: true

# Build settings
gems:
  - jekyll-paginate-v2
  - jekyll-feed
  - autoprefixer-rails
  - jekyll-assets

sass:
  implementation: 'sass-embedded'
  sass_dir: 'assets/css'
  load_paths:
    - 'assets/css/*'

# Pagination configuration
pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2

# Default Front Matter
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "md"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "md"
  -
    scope:
      path: "./*.md"
    values:
      layout: "md"
  -
    scope:
      path: "./*.markdown"
      type: "pages"
    values:
      layout: "md"

# Exclude from processing.
exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - .sass-cache/
  - .jekyll-cache/
  - README.md
    
# Include scss for things
# include:
#   - assets/css/*
