# Site settings
title: Jared Tulayan
description: >-
  Rutgers Computer Science student
baseurl: ""
url: ""
domain: "jaredtulayan.xyz" # This is here for ease of access
permalink: /blog/:title:output_ext
highlighter: none

# Contact info
email: jared@jaredtulayan.xyz
phone: +1 (609) 361-4018
telegram: Endoman123
github:  endoman123
instagram:  jared.tulayan

# Custom collections
collections:
  projects:
    output: true

# Build settings
plugins:
  - jekyll-paginate-v2
  - jekyll-feed
sass:
  sass_dir: 'assets/css'

# Pagination configuration
pagination:
  enabled: true
  debug: true
  trail: 
    before: 2
    after: 2
  per_page: 10
  offset: 0
  permalink: '/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Default Front Matter
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "md"
      draft: true
  -
    scope:
      path: "./*.md"
      type: "pages"
    values:
      layout: "md"
  -
    scope:
      path: "./*.markdown"
      type: "pages"
    values:
      layout: "md"

# Exclude from processing.
exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - .sass-cache/
  - .jekyll-cache/
  - assets/css/*/*
